root_files:
  - { input: 01-revision.hu, variants: true }
  - { input: 02-operators.hu, variants: true }
  - { input: 03-potential.hu, variants: true }
  - { input: 04-line-integrals.hu, variants: true }
  - { input: 05-surface-integrals.hu, variants: true }
  - { input: 06-integral-theorems.hu, variants: true }
  - { input: 07-summary.hu, variants: true }
