root_files:
  - { input: revision.hu, variants: true }
  - { input: operators.hu, variants: true }
  - { input: line-integrals.hu, variants: true }
  - { input: surface-integrals.hu, variants: true }
  - { input: integral-theorems.hu, variants: true }
  - { input: summary.hu, variants: true }
