root_files:
  - { input: rank.hu, output: rank-hu }
  - { input: transformations.hu, output: transformations-hu }
  - { input: cramers-rule-singularity.hu, output: cramers-singularity-hu }
  - { input: determinant-theorem-usage.hu, output: determinant-theorems-hu }
out_dir: build
